# Create a jekyll container from a ruby alpine image

# at min, use ruby 2.5
FROM ruby:2.7-alpine3.15

# add jekyll dependences 
RUN apk update
RUN apk add --no-cache build-base gcc cmake git


# update ruby bundler 
RUN gem update bundler && gem install bundler jekyll